### ISSUE TITLE
Add Allstart github app

### ISSUE THREAD

**Issue by Gby56** [security-alert/security-alert#31]
We should add some safeguards and security checks in the repo to show good practices are in place
What do you think about adding https://github.com/ossf/allstar ? @azu

**Comment by azu** [comment]
I think that [Allstar](https://github.com/ossf/allstar) is for a orgnization, but it is useful for checking.
Also, We can move this repo to a org like `security-alert/security-alert`.

Maybe, it is better that move this repo to org if we will use allstar app.
Because, GitHub App installation requires owner permission of the orgnization or the repository.
It means I am the only one who can install GitHub Apps.(It is limitation of personal repository)

If we have moved to org, orgnization owners(I and you) can install GitHub Apps.
It will avoid SPOF(Single Point of Failure).

**Comment by azu** [comment]
OK. I will create `security-alert` and transfer this to the org.
